config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :announcments
  end

  root 'announcments#index'
  post '/announcments/:id', to: 'comments#create', as: :new_comment

  resources :announcments
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', confirmations: 'users/confirmations',
                                    registrations: 'users/registrations'}

end

app/models/announcment.rb
class Announcment < ApplicationRecord
  belongs_to :user
  has_many :comments
  mount_uploader :logo, AvatarUploader
end

app/controllers/announcments_controller.rb
class AnnouncmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_annocuments, only: [:edit, :update, :destroy, :show]
  layout 'application'
  def index
    @annoucnments = Announcment.all

    # render json: @annoucnments

  end

  def new
    @annoucnment = current_user.announcments.new
  end

  def create
    @annoucnment = current_user.announcments.build(annoucment_params)

    if @annoucnment.save
      redirect_to root_path, notice: 'Annoucment has been created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @annoucnment.update_attributes(annoucment_params)
      redirect_to root_path, notice: 'Anncoucment has been updated'
    else
      render :edit
    end
  end

  def show
    @comments = @annoucnment.comments.all
    expires_in 3.minutes, :public => true
    # render json: @annoucnment
  end

  def destroy

  end

  private

  def annoucment_params
    params.require(:announcment).permit(:title, :body, :logo, :user_id)
  end

  def set_annocuments
    @annoucnment = Announcment.find(params[:id])
  end
end

app/controllers/api/announcments_controller.rb
class Api::AnnouncmentsController < Api::ApiController

    def create
      annoucnment = current_user.announcments.build(annoucment_params)

      if annoucnment.save
        render status: 200, json: {
            message: 'Successfully created an annoucment',
            annoucnment: annoucnment
        }.to_json
      else

        render status: 422, json: {
            errors: annoucnment.errors
        }.to_json

      end
    end


  def show
    announcment = Announcment.find(params[:id])

    if stale?(announcment)
      render json: announcment.as_json(only: [:id, :title, :body, :logo], include:{user: {only:[:id, :name], include: {department:{only: [:id,:name]}}},
                                                                                   comments: {only: [:content], include:{user:{only: [:id, :name], include:{department:{only: [:id, :name]}}}}}})
    end


  end

  private
  def annoucment_params
    params.require(:announcment).permit(:title, :body, :logo, :user_id)
  end
end

app/helpers/announcments_helper.rb
module AnnouncmentsHelper
end

app/views/announcments/_form.html.erb
<%= form_for @annoucnment do |f|%>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <% if @annoucnment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@annoucnment.errors.count, "errors") %> forbidden to save this announcement:</h2>
            <ul>
              <% @annoucnment.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-4">

      <div class="col-xs-12 col-sm-12 col-md-12">
        <%= f.label 'Image' %>
        <%= f.file_field :logo %>
      </div>


      <div class="col-xs-12 col-sm-12 col-md-12">
        <%= f.label 'Title' %>
        <%= f.text_field :title, placeholder: 'Title*', :class => "form-control" %>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-12">
        <%= f.label 'Body' %>
        <%= f.text_area :body, placeholder: 'Body*', :class => "form-control" %>
      </div>


        <div class="action">
          <%= f.submit  %>
        </div>
    </div>
<%end %>

app/views/announcments/edit.html.erb
<%= render 'form' %>

app/views/announcments/index.html.erb
<div class="container-fluid">
  <%= link_to 'Create new one', new_announcment_path, class: 'btn btn-success' %>
  <% if user_signed_in? %>
  <%= link_to 'Log out', destroy_user_session_path, :method => :delete  %>
  <%else %>
  <%= link_to 'Login', new_user_session_path %> |
      <%= link_to 'Register', new_user_registration_path %>
  <%end %>
  <div>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>logo</th>
      <th>User name</th>
      <th>Department</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% @annoucnments.each do |a| %>
    <tr>
          <td><%= a.title %></td>
          <td><%= truncate(a.body, length: 50) %></td>
          <td><%= image_tag(a.logo, size: '50x50') %></td>
          <td><%= a.try(:user).try(:name) %></td>
          <td><%= a.try(:user).try(:department).try(:name) %></td>
          <td>
            <%= link_to 'JSON single', api_announcment_path(a) %> |
            <%= link_to 'HTML single', announcment_path(a.id) %>
          </td>
    </tr>
    <%end %>
    </tbody>
  </table>
  </div>
</div>

app/views/announcments/new.html.erb
<%= render 'form' %>

app/views/announcments/show.html.erb
<div class="container-fluid">

  <div class="row">
    <div class="col-md-8">
      <h4><b>Annoucment information</b></h4>
      <div>
        <strong>Title</strong>
        <p><%= @annoucnment.title %></p>
      </div>


      <div>
        <strong>Body</strong>
        <p><%= @annoucnment.body %></p>
      </div>

      <div>
        <strong>Image</strong>
        <p><%= image_tag(@annoucnment.logo, size: '100x100') %></p>
      </div>

      <div>
        <strong>User Name</strong>
        <p><%= @annoucnment.try(:user).try(:name)  %></p>
      </div>

      <div>
        <strong>Department</strong>
        <p><%= @annoucnment.try(:user).try(:department).try(:name) %></p>
      </div>
    </div>
    <div class="col-md-4">
      <h4><b>Comment about annoucment</b></h4>

      <% @comments.each do |c| %>
          <div>
            <%= c.try(:user).try(:name) %>:
            <%= c.content %>
          </div>

      <%end %>

      <%= form_tag(new_comment_path(@annoucnment.id), method: :post, remote: true) do %>
          <%= hidden_field_tag :user_id,  current_user.id %>
          <%= text_area_tag :content %>
          <%= submit_tag 'Send' %>
      <% end %>
    </div>
  </div>

</div>